channels:
  - conda-forge
dependencies:
  - r-base=4.0
  - r-tidyverse
  - r-fbasics
  - r-corrplot
  - r-psych
  - r-glmnet
  - r-glmnetutils
  - r-grf
  - r-rpart
  - r-rpart.plot
  - r-treeclust
  - r-randomforest
  - r-rlang
  - r-readr
  - r-devtools
  - r-reshape2
  - r-caret
  - r-plotmo
  - r-randomfieldsutils
  - r-rms
  - r-hdm
  - r-aer
  - r-lmtest
  - r-dplyr
  - r-sandwich
  - r-diagrammer
  - r-neuralnet
  - r-data.table 
  - r-rvest
  - r-httr
  - r-jsonlite
  - r-xml2
  - r-tm
  - r-tidytext
  - r-topicmodels
  - r-wordcloud
  - r-naivebayes
  - r-slam
  - r-lexicon
  - r-gmodels
  - r-qdap

